# Generated by Django 3.0.4 on 2020-08-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
