# Generated by Django 3.0.4 on 2020-08-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0003_downloadedsongs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadedSongs',
        ),
    ]
