# Generated by Django 3.0.4 on 2020-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0004_delete_downloadedsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150, unique=True)),
                ('artist_name', models.CharField(max_length=150)),
            ],
        ),
    ]
