# Generated by Django 3.0.4 on 2020-08-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0005_downloadedsongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='downloaded',
        ),
    ]
