# Generated by Django 3.0.4 on 2020-08-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0007_song_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='downloaded',
            field=models.BooleanField(),
        ),
    ]
