# Generated by Django 3.0.4 on 2020-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0008_auto_20200825_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
