# Generated by Django 3.0.4 on 2020-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0009_auto_20200825_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='video_title',
        ),
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
