# Generated by Django 3.2 on 2021-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfflinePlaylist', '0010_auto_20200902_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
